# -*- coding: utf-8 -*-
"""SHIELD.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dFDaU9jZ9FMoTM4a4SzBVESclZbyNQN3
"""

!pip install scikit-learn matplotlib pandas

import pandas as pd
import numpy as np
from google.colab import files
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap

print("=== S.H.I.E.L.D FLOODSCOPE (2025) by Saad Ali ===")

"""Upload CSV file with columns: id,elev,slope,lulc,soil,cn   create 37 rows:.  0=center, 1-36=6x6 grid)

Make a copy to proceed:
https://docs.google.com/spreadsheets/d/1IvLQsOliTf0UMMjvgj9D8yaozXSGRVr1quZ2IWoaBNQ/edit?usp=sharing
"""

## Run to upload CSV ##


uploaded = files.upload()
df = pd.read_csv(next(iter(uploaded)))
print(f"Loaded {len(df)} points\n{df.head()}")

"""Flood Risk Scoring and Diplay"""

## FLOOD RISK SCORING ##


def flood_risk_score(row):
    score = 0
    # LOW ELEVATION = HIGH RISK
    if row['elev'] < df['elev'].quantile(0.33): score += 2
    # GENTLE SLOPE = HIGH RISK
    if row['slope'] < 3: score += 2
    elif row['slope'] < 9: score += 1
    # HIGH CURVE NUMBER = HIGH RUNOFF
    if row['cn'] > 75: score += 3
    elif row['cn'] > 70: score += 2
    elif row['cn'] > 65: score += 1
    # BUILT-UP LAND = HIGH RISK
    if row['lulc'] == 1: score += 2  # Built-up
    elif row['lulc'] == 3: score += 1  # Grass
    # POOR SOIL = HIGH RUNOFF
    if row['soil'] == 3: score += 2  # HSG-C
    elif row['soil'] == 2: score += 1  # HSG-B

    # 5 RISK CLASSES (0-4)
    return min(4, max(0, score//2))

df['risk'] = df.apply(flood_risk_score, axis=1)

## GRID VISUALIZATION ##


grid = df[df['id'].between(1,36)]['risk'].values.reshape(6,6)
center_risk = df.loc[0, 'risk']

fig, axes = plt.subplots(1,2 , figsize=(12,4))
cmap = ListedColormap(['#d9f0d3','#a1d99b','#41ab5d','#005a32','#003300'])

elev_min, elev_max = df['elev'].min(), df['elev'].max()
cn_min, cn_max = df['cn'].min(), df['cn'].max()

# Elevation Chart
im0 = axes[0].imshow(df[df['id'].between(1,36)]['elev'].values.reshape(6,6), cmap='terrain', vmin=elev_min, vmax=elev_max)
axes[0].set_title('Elevation')
cbar0 = fig.colorbar(im0, ax=axes[0], shrink=0.8)
cbar0.set_ticks([elev_min, (elev_min + elev_max)/2, elev_max])
cbar0.set_ticklabels(['Low Elevation', 'Mid Elevation', 'High Elevation'])

# Curve Number Chart
im1 = axes[1].imshow(df[df['id'].between(1,36)]['cn'].values.reshape(6,6), cmap='Reds', vmin=cn_min, vmax=cn_max)
axes[1].set_title('Curve Number')
cbar1 = fig.colorbar(im1, ax=axes[1], shrink=0.8)
cbar1.set_ticks([cn_min, (cn_min + cn_max)/2, cn_max])
cbar1.set_ticklabels(['Low Curve Number', 'Mid Curve Number', 'High Curve Number'])

plt.tight_layout()

# FLOOD RISK MAP AND RISK DISTRIBUTION SIDE-BY-SIDE

grid = df[df['id'].between(1,36)]['risk'].values.reshape(6,6)
center_risk = df.loc[0, 'risk']

risk_cmap = ListedColormap(['#d9f0d3','#a1d99b','#41ab5d','#005a32','#003300'])

fig, axes = plt.subplots(1, 2, figsize=(15, 4))

im = axes[0].imshow(grid, cmap=risk_cmap, vmin=0, vmax=4)
axes[0].scatter(2.5, 2.5, c='black', s=400, marker='*', edgecolors='white', linewidths=2)
axes[0].set_title(f'Flood Risk Map ({len(df)} points analyzed)')
axes[0].set_xticks([])
axes[0].set_yticks([])

cbar = fig.colorbar(im, ax=axes[0], ticks=[0,1,2,3,4], shrink=0.8)
cbar.ax.set_yticklabels(['Very Low','Low','Moderate','High','Very High'])

# Define risk_counts before using it
risk_counts = df['risk'].value_counts().sort_index()

axes[1].pie(risk_counts.values, labels=[f'{i} ({v} pts)' for i,v in risk_counts.items()],
              colors=risk_cmap.colors, autopct='%1.0f%%')
axes[1].set_title('Risk Distribution')

fig.suptitle(f'Flood Risk Overview ({len(df)} points analyzed)', fontsize=16)

plt.tight_layout()

plt.savefig('flood_risk_overview.png', dpi=300, bbox_inches='tight')
plt.show()

df.to_csv('flood_risk_results.csv', index=False)
files.download('flood_risk_results.csv')
files.download('flood_risk_overview.png')

## SUMMARY ##


risk_counts = df['risk'].value_counts().sort_index()

df.to_csv('flood_risk_results.csv', index=False)
files.download('flood_risk_results.csv')

print("\n ANALYSIS COMPLETE")
print(df[['id','elev','slope','cn','risk']].round(1))
print(f"\nCenter point risk: {center_risk}")